<?xml version="1.0"?>
<package format="3">
  <name>ground_vehicle_kinematics</name>
  <version>0.7.0</version>
  <description>
    Package to compute direc and inverse kinematics for ground vehicles
  </description>
  <maintainer email="jfrascon@gmail.com">Juan Francisco Rascon Crespo</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>eigen</build_depend>
  <build_export_depend>eigen</build_export_depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>eigen</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ros2_launch_helpers</exec_depend>

  <depend>angles</depend>
  <depend>actuator_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>rclcpp</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
