/**/three_swerve_kinematics:
  ros__parameters:
    # use_sim_time IS automatically handled, no need to specify here.

    kinematics_solver_type: "mixed" # direct: JointState->Twist, inverse: Twist->JointState, mixed: run both flows.
    inverse_kinematics_solver_initialization_timeout: 10.0 # seconds to wait for the initial JointState seed.

    steerable_wheels:
      steerable_wheel_a:
        name: "wheel_1"
        radius: 0.10
        steerable_joint:
          name: "wheel_1_steerable_joint"
          parent_link_name: "base_link"
          child_link_name: "wheel_1_steerable_link"
          origin: { x: -0.35, y: -0.25, z: 0.0, R: 0.0, P: 0.0, Y: 0.0 }
          angular_limits: { lower: -3.14159, upper: 3.14159 } # Solver enforces continuity within these bounds.
        rotation_joint:
          name: "wheel_1_joint"
          parent_link_name: "wheel_1_steerable_link"
          child_link_name: "wheel_1_link"
          origin: { x: 0.0, y: 0.0, z: -0.1, R: 0.0, P: 0.0, Y: 0.0 }

      steerable_wheel_b:
        name: "wheel_2"
        radius: 0.10
        steerable_joint:
          name: "wheel_2_steerable_joint"
          parent_link_name: "base_link"
          child_link_name: "wheel_2_steerable_link"
          origin: { x: -0.35, y: 0.25, z: 0.0, R: 0.0, P: 0.0, Y: 0.0 }
          angular_limits: { lower: -3.14159, upper: 3.14159 }
        rotation_joint:
          name: "wheel_2_joint"
          parent_link_name: "wheel_2_steerable_link"
          child_link_name: "wheel_2_link"
          origin: { x: 0.0, y: 0.0, z: -0.1, R: 0.0, P: 0.0, Y: 0.0 }

      steerable_wheel_c:
        name: "wheel_3"
        radius: 0.10
        steerable_joint:
          name: "wheel_3_steerable_joint"
          parent_link_name: "base_link"
          child_link_name: "wheel_3_steerable_link"
          origin: { x: 0.35, y: 0.0, z: 0.0, R: 0.0, P: 0.0, Y: 0.0 }
          angular_limits: { lower: -3.14159, upper: 3.14159 }
        rotation_joint:
          name: "wheel_3_joint"
          parent_link_name: "wheel_3_steerable_link"
          child_link_name: "wheel_3_link"
          origin: { x: 0.0, y: 0.0, z: -0.1, R: 0.0, P: 0.0, Y: 0.0 }
